name: External Testing

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  aave-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      env:
        SEED_WORDS: ${{ secrets.seedWords }}
        INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}    
      run: |
        yarn
        sudo apt-get install mmv
    - name: Run tools (network)
      run: |
        docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
        sudo chmod go+r /etc/hosts
        sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
        git clone https://github.com/nevermined-io/tools
        cd tools
        git checkout set-rpc-port
        export KEEPER_RPC_PORT="18545"
        export KEEPER_NETWORK_NAME="spree"
        export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
        export GANACHE_COMMAND_OPTIONS="-d -i 8996 -p 18545 -m 'taxi music thumb unique chat sand crew more leg another off lamp' -u 0xAFD49D613467c0DaBf47B8f5C841089d96Cf7167 -f https://eth-kovan.alchemyapi.io/v2/UaH4LeYR7hHlx00yQZanF1B5AUSmDsTA@28000000"
        export KEEPER_VERSION=develop
        export GATEWAY_VERSION=develop
        export COMPUTE_API_VERSION=latest
        export METADATA_VERSION=latest
        ./start_nevermined.sh --marketplace-api --no-marketplace --no-faucet --no-graph --local-ganache-node 2>&1 | tee nevermined_tools.txt &
        cd ..
        ./scripts/wait-nevermined-external.sh
    - name: Run aave integration test
      run: |
        export ETH_PORT=18545
        npm run integration:aave
    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: nevermined-tools-output
        path: tools/nevermined_tools.txt
