name: Testing w/ Nevermined Node depending on SDK changes

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/node
          ref: 'develop' # TODO: Remove this when ready to use main branch
          path: node
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/sdk-dtp
          ref: develop
          path: sdk-dtp
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: nevermined-io/nvm-tools-actions@v0.3.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: "true"
          estuary: "true"
          compute: "true"
          node: "false"
          contracts-version: "v3.0.0-rc2"

      - name: Install dependencies
        run: yarn

      - name: Build SDK-JS package and node
        run: |
          yarn build
          yarn pack
          cp *.tgz sdk-dtp/sdk.tgz
          cp *.tgz node/sdk.tgz
          cd sdk-dtp
          sed -i "/sdk-js/c\\    \"@nevermined-io/nevermined-sdk-js\": \"./sdk.tgz\"," package.json
          yarn
          yarn build
          yarn pack
          cp *dtp*.tgz ../node/dtp.tgz

          cd ../node
          sed -i "/sdk-js/c\\    \"@nevermined-io/nevermined-sdk-js\": \"./sdk.tgz\"," package.json
          sed -i "/sdk-dtp/c\\    \"@nevermined-io/nevermined-sdk-dtp\": \"./dtp.tgz\"," package.json
          yarn
          yarn run setup:dev
          yarn build

      - name: Run node
        env:
          WEB3_PROVIDER_URL: http://contracts.nevermined.localnet
          # estuary token for local development
          ESTUARY_TOKEN: ESTaa43688b-4ccf-4dad-8a16-410e488706ffARY
          ESTUARY_ENDPOINT: http://estuary.nevermined.localnet
          ENABLE_COMPUTE: "true"
          ARGO_HOST: "true"
          ARGO_NAMESPACE: "true"
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        run: |
          cd node
          export ARGO_AUTH_TOKEN=$(kubectl get secret -n nevermined argo-workflow-token -o jsonpath='{.data.token}' | base64 --decode)
          export MINIO_ACCESS_KEY=$(kubectl get secret -n nevermined minio-access-key -o jsonpath='{.data.accesskey}' | base64 --decode)
          export MINIO_SECRET_KEY=(kubectl get secret -n nevermined minio-secret-key -o jsonpath='{.data.secretkey}' | base64 --decode)
          nvm-tools copy-artifacts ./artifacts
          yarn start 2>&1 | tee node_log.txt &

      - name: Run integration tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          IPFS_GATEWAY: https://ipfs.infura.io:5001
          IPFS_PROJECT_ID: ${{ secrets.IPFS_PROJECT_ID }}
          IPFS_PROJECT_SECRET: ${{ secrets.IPFS_PROJECT_SECRET }}
          NEVERMINED_NODE_URI: http://localhost:8030
          NO_GRAPH: true
        run: |
          nvm-tools copy-artifacts ./artifacts
          yarn run integration:cover

      - name: Upload node logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: node-output
          path: node/node_log.txt
