name: Testing Compute

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nevermined-io/nvm-tools-actions@v0.9.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: 'true'
          estuary: 'true'
          compute: 'true'
          contracts-version: 'v3.1.0'

      - name: Install dependencies
        run: |
          yarn

      - name: Check artifacts
        run: |
          nvm-tools copy-artifacts ./artifacts
          ls -l artifacts

      - name: Run compute integration tests
        env:
          SEED_WORDS: ${{ secrets.seedWords }}
          NO_GRAPH: true
          NEVERMINED_NODE_URI: http://node.nevermined.localnet
          WEB3_PROVIDER_URL: http://contracts.nevermined.localnet
        run: |
          yarn run integration:compute
