name: Tests Nightly

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nevermined-io/nvm-tools-actions@v0.7.1
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: 'true'
          estuary: 'true'
          compute: 'true'
          contracts-version: 'v3.0.0'
          node-version: 'develop'

      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: yarn lint

      - name: Check artifacts
        run: |
          nvm-tools copy-artifacts ./artifacts
          ls -l artifacts

      - name: Start ganache
        run: yarn ganache --port 18545 --chain.chainId 8998 &

      - name: Run unit tests
        env:
          ETH_PORT: 18545
        run: |
          yarn run test:cover

      - name: Run subgraph integration tests
        env:
          SEED_WORDS: ${{ secrets.seedWords }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
        run: |
          export ${{ matrix.delay }}=true
          npm run integration:subgraph

      - name: Run compute integration tests
        env:
          SEED_WORDS: ${{ secrets.seedWords }}
          NO_GRAPH: true
          NEVERMINED_NODE_URI: http://node.nevermined.localnet
          WEB3_PROVIDER_URL: http://contracts.nevermined.localnet
        run: |
          yarn run integration:compute


      - name: Run external tests
        env:
          SEED_WORDS: ${{ secrets.seedWords }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          IPFS_GATEWAY: https://ipfs.infura.io:5001
          IPFS_PROJECT_ID: ${{ secrets.IPFS_PROJECT_ID }}
          IPFS_PROJECT_SECRET: ${{ secrets.IPFS_PROJECT_SECRET }}
          LOG_LEVEL: 1 # If LOG_LEVEL is >1 it will print the logger.debug calls
          NO_GRAPH: true
        run: yarn run integration:external


      - name: Run integration tests
        env:
          SEED_WORDS: ${{ secrets.seedWords }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          IPFS_GATEWAY: https://ipfs.infura.io:5001
          IPFS_PROJECT_ID: ${{ secrets.IPFS_PROJECT_ID }}
          IPFS_PROJECT_SECRET: ${{ secrets.IPFS_PROJECT_SECRET }}
          LOG_LEVEL: 1 # If LOG_LEVEL is >1 it will print the logger.debug calls
          NO_GRAPH: true
        run: yarn run integration:cover

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          yarn

      - name: Download artifacts
        run: |
          mkdir -p node_modules/@nevermined-io/contracts/artifacts
          yarn artifacts:download v3.0.0 mumbai public
          ls -l node_modules/@nevermined-io/contracts/artifacts

      - name: Run nightly tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC_NIGHTLY }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          IPFS_GATEWAY: https://ipfs.infura.io:5001
          IPFS_PROJECT_ID: ${{ secrets.IPFS_PROJECT_ID }}
          IPFS_PROJECT_SECRET: ${{ secrets.IPFS_PROJECT_SECRET }}
        run: |
          yarn integration:e2e:mumbai
