name: Testing w/ Nevermined Node depending on SDK changes

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--geth"]
        node: ["16"]
        include:
          - network: "--geth"
            network-name: geth-localnet
            chainId: 8998

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: yarn lint
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/node
          path: node
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/sdk-dtp
          path: sdk-dtp
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Build SDK-JS package and node
        run: |
          yarn build
          yarn pack
          cp *.tgz sdk-dtp/sdk.tgz
          cp *.tgz node/sdk.tgz
          cd sdk-dtp
          sed -i "/sdk-js/c\\    \"@nevermined-io/nevermined-sdk-js\": \"./sdk.tgz\"," package.json
          yarn
          yarn build
          yarn pack
          cp *dtp*.tgz ../node/dtp.tgz

          cd ../node
          sed -i "/sdk-js/c\\    \"@nevermined-io/nevermined-sdk-js\": \"./sdk.tgz\"," package.json
          sed -i "/sdk-dtp/c\\    \"@nevermined-io/nevermined-sdk-dtp\": \"./dtp.tgz\"," package.json
          yarn
          yarn run setup:dev
          yarn build

      - name: Run tools (network)
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
          git clone https://github.com/nevermined-io/tools
          cd tools

          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

          # Disabling the compute api for now
          # Check https://github.com/nevermined-io/sdk-js/issues/33
          
          # TODO: Use the default Node when merged into master
          ./start_nevermined.sh ${{ matrix.network }} --no-graph --no-node --opengsn 2>&1 | tee nevermined_tools.txt &
          cd ..
          ./scripts/wait-nevermined.sh

      - name: Run node
        run: |
          cd node
          ./scripts/wait-nevermined.sh
          yarn start 2>&1 | tee node_log.txt &

      - name: Run integration tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          OLD_GATEWAY: false
          NO_GRAPH: true
        run: |
          yarn run integration:cover
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: node-output
          path: node/node_log.txt
