name: Testing w/ Nevermined Node depending on SDK changes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/node
          path: node
          # TODO: remove this when Node integrated with SDKv2 is integraged
          ref: develop
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: nevermined-io/nvm-tools-actions@v0.14.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: 'true'
          estuary: 'true'
          contracts-version: 'v3.2.1'
          node: 'false'

      - name: Install dependencies
        run: yarn

      - name: Build SDK-JS package and node
        run: |
          yarn build

          cd node/
          yarn add ../
          yarn run setup:dev
          yarn build

      - name: Run node
        env:
          WEB3_PROVIDER_URL: http://contracts.nevermined.localnet
          # estuary token for local development
          ESTUARY_TOKEN: ESTaa43688b-4ccf-4dad-8a16-410e488706ffARY
          ESTUARY_ENDPOINT: http://estuary.nevermined.localnet
        run: |
          cd node
          nvm-tools copy-artifacts ./artifacts
          yarn start 2>&1 | tee node_log.txt &

      - name: Run integration tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          IPFS_GATEWAY: https://ipfs.infura.io:5001
          IPFS_PROJECT_ID: ${{ secrets.IPFS_PROJECT_ID }}
          IPFS_PROJECT_SECRET: ${{ secrets.IPFS_PROJECT_SECRET }}
          NEVERMINED_NODE_URI: http://localhost:8030
        run: |
          nvm-tools copy-artifacts ./artifacts
          yarn integration:all

      - name: Upload node logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: node-output
          path: node/node_log.txt
